### ISSUE TITLE
dgenies doesn't run

### ISSUE THREAD

**Issue by aderzelle** [genotoul-bioinfo/dgenies#4]
Hello, 
when calling "dgenies run" I get the following error message 
`Traceback (most recent call last):
  File "/usr/local/bin/dgenies", line 4, in <module>
    __import__('pkg_resources').run_script('dgenies==1.2.0', 'dgenies')
  File "/home/alessandro/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 661, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/alessandro/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1432, in run_script
    .format(**locals()),
pkg_resources.ResolutionError: Script 'scripts/dgenies' not found in metadata at '/home/alessandro/.local/lib/python3.6/site-packages/dgenies-1.2.0.dist-info'`

OS is Ubuntu 18.04.1

I am not familiar with python though.  
Thank you

**Comment by mpcox** [comment]
I get this exact same error too.

**Comment by florealcab** [comment]
Hi,
Thank you for reporting. How do you install it? Can you give me the command lines?

It's probably due to python 3.6, as we only test over python3.5.

I have an Ubuntu 18.04 here, I have an error too (not the same, stangely). I'll try to fix it as soon as possible.

Regards,
Floréal Cabanettes

**Comment by mpcox** [comment]
Thanks, Floréal.

Initially I installed as root (pip3 install dgenies), which worked without error. But at runtime, I got the error exactly as described here:
https://github.com/genotoul-bioinfo/dgenies/issues/3

I tried the fix proposed by @dwinter, but as the installation was run as root, not as user (--user), changing ~/.dgenies had no effect.

I then uninstalled, and tried installing using the git clone approach. That's when I got the error noted above.

I am running macOS 10.13.6, which I realize is not Ubuntu, but since the errors are identical, I don't think the OS is the issue.  I'm running python 3.6.6, which as you say, might be the problem.

Incidentally, if it is helpful for testing purposes, I'm in the same group as @dwinter

Finally, this really does seem like a lovely piece of software - much better than others that I have tried over the years. Well done!

**Comment by aderzelle** [comment]
Hello,
It is working now with the anaconda install. Not exactly sure what happened, but, well, it works ;) 
Thanks!

**Comment by mpcox** [comment]
Hello, that sounds promising.
A question: which install option do you mean by 'the anaconda install'?

**Comment by aderzelle** [comment]
Sorry indeed not very clear. 
I installed anaconda3 and was then able to install Dgenies and make it work. I guess this suggests there was some python3 dependency problem.

**Comment by mpcox** [comment]
Ah, this sounds very promising. I don't suppose you could list your explicit install instructions? I could play around, but it would be cleaner if I can repeat exactly what you did?

**Comment by florealcab** [comment]
If you install through "git clone", you must run:
pip install -r requirements.txt
This should install all requirements.

**Comment by aderzelle** [comment]
I was setting up a new machine so I installed so many things 
But I think something of the sort happened
- install with the default python3 of Ubuntu: didn't launch properly 
- install anaconda3 for other purposes
- tried again with Dgenies and this time it worked.

**Comment by florealcab** [comment]
Hi,

There was the strange bug with the current version on the pypi repo.

So, I repackage it and now it works perfectly.

@mpcox can you try reinstalling it with:
sudo pip3 install dgenies

It should install the 1.2.0.1 version, right?

Then, this should work:
dgenies run

Do you confirm that?

**Comment by mpcox** [comment]
Woo hoo! Installs perfectly.
Thanks very much again for this. You've been very very helpful.  And it really is a lovely piece of software.

**Comment by florealcab** [comment]
Good news! :)
