### ISSUE TITLE
Running out of disk space and/or memory?

### ISSUE THREAD

**Issue by anandksrao** [genotoul-bioinfo/dgenies#8]
Happy New Year 2019 to the D-GENIES team!

**System info**
I am running D-GENIES on Ubuntu 18.04.1 LTS inside VirtualBox 6.6.0 on my MacOSX laptop with 8G RAM. So my RAM available on the virtual machine is 6.5GB

Several of my pairwise genome alignment runs locally on the Apache2 HTTP web server complete successfully. I am using gzip fasta files that are originally up to 2GB large. But so far I've only tested with max input file size of ~ 650MB & ~ 650MB pair of files.

**Problems**
However, some of the runs fail
A. with no explicit reason provided, or
B. because I ran out of memory for that run.

**Modification tried, but with with no success**
I saw your post for resolved issue #3, here about altering application.properties. 
I bumped up input file size to 4GB, but had to reduce memory available to 6.5GB.

**How to free up disk space?**
Furthermore, it appears I have a lot of disk space that is occupied by files that have appeared only after I installed and stared using D-GENIES (I think):
572K	anand/.cache/pip/http/6/7/2
948K	anand/.cache/pip/http/6/7
256K	anand/.cache/pip/http/6/8/4/6/f
260K	anand/.cache/pip/http/6/8/4/6
264K	anand/.cache/pip/http/6/8/4
Interestingly,  I am unable to individually list these files / folders!

**My questions are:**
1. How can I free up my disk space?
2. Is there any work-around for using lower RAM? i can only use local machine since university cluster does not support Virtual Machines.
3. Is there an empirical guesstimate for RAM required based on input file size?
4. For input files that will require more RAM than I have on my local machine, is there any work-around?

Since I am a newbie to D-GENIES, VirtualBox and APACHE2, my questions may be rudimentary. But thanks very much for helping with my troubleshooting.

Cheers,
Anand

**Comment by Bios4Biol** [comment]
D-Genies memory usage is mainly correlated to the aligner memory usage.

 **How can I free up my disk space?**

To clean the used disk you can use 
dgenies clear -l 
as presented in "maintenance" section of http://dgenies.toulouse.inra.fr/install

**Is there any work-around for using lower RAM? i can only use local machine since university cluster does not support Virtual Machines.**

You can try to change the aligner used by D-Genies. This is presented in the "Add or change alignment tools" section of the same page.

**Is there an empirical guesstimate for RAM required based on input file size?**

No, because the memory space used by the aligner depends on the sequence composition of your query and target. A given sequence size can generate very different alignments and memory usages.
You could try to align your sequences with minimap2 (command line) and then use D-Genies to plot the alignment. See 'plot alignment' in the run section of the user interface. 

**For input files that will require more RAM than I have on my local machine, is there any work-around?**

If the alignment processing does not fit in the memory space of your machine, there is no work-around. You have to find a server with more RAM.
